[2023-09-04 15:38:24,274][    INFO] {'backbone': 'resnet101',
 'batch_size': 2,
 'conf_thresh': 0.95,
 'config': 'configs/pascal.yaml',
 'criterion': {'kwargs': {'ignore_index': 255}, 'name': 'CELoss'},
 'crop_size': 321,
 'data_root': '/root/data/VOC2012',
 'dataset': 'pascal',
 'dilations': [6, 12, 18],
 'epochs': 80,
 'labeled_id_path': 'splits/pascal/732/labeled.txt',
 'local_rank': 0,
 'lr': 0.001,
 'lr_multi': 10.0,
 'model': 'deeplabv3plus',
 'nclass': 21,
 'ngpus': 1,
 'port': 19500,
 'replace_stride_with_dilation': [False, False, True],
 'save_path': 'exp/pascal/unimatch/r101/732',
 'unlabeled_id_path': 'splits/pascal/732/unlabeled.txt'}

Traceback (most recent call last):
  File "unimatch.py", line 250, in <module>
    main()
  File "unimatch.py", line 53, in main
    model = DeepLabV3Plus(cfg)
  File "/root/code/exp/UniMatch/model/semseg/deeplabv3plus.py", line 14, in __init__
    self.backbone = resnet.__dict__[cfg['backbone']](pretrained=True, 
  File "/root/code/exp/UniMatch/model/backbone/resnet.py", line 163, in resnet101
    return _resnet('resnet101', Bottleneck, [3, 4, 23, 3], pretrained, **kwargs)
  File "/root/code/exp/UniMatch/model/backbone/resnet.py", line 153, in _resnet
    state_dict = torch.load(pretrained_path)
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/resnet101.pth'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 46808) of binary: /root/env/mamba/envs/mmseg/bin/python3.8
Traceback (most recent call last):
  File "/root/env/mamba/envs/mmseg/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/env/mamba/envs/mmseg/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
unimatch.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-04_15:38:30
  host      : 094a3af38c4f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 46808)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
